name: RoyalMessages
main: org.royaldev.royalmessages.RoyalMessages
version: 0.0.2
softdepend: [Vault, Multiverse-Core]
website: http://dev.royaldev.org/
author: jkcclemens

commands:
  rmessages:
    description: Reloads RoyalMessages' config and displays version number.
    usage: /<command>