name: rMessages
main: org.royaldev.royalmessages.rMessages
version: 0.0.3
softdepend: [Vault, Multiverse-Core]
website: https://github.com/lelodude/RoyalMessages
author: Lelo

commands:
  rmessages:
    description: Reloads RoyalMessages' config and displays version number.
    usage: /<command>